### ISSUE TITLE
Use the criterion crate for benchmarking intead of test::Bencher

### ISSUE THREAD

**Issue by mssun** [yogcrypt/yogcrypt#7]
I found that the `criterion` crate is a good replacement for the test Bencher.
  - it doesn't require Rust nightly
  - it supports more benchmark customization
  - even, it can draw graph
  - etc

Also, the `curve25519-dalek` project uses it too, which means that this crate can be used  as a benchmark util for crypto library.

Reference:
  - https://github.com/japaric/criterion.rs
  - https://github.com/dalek-cryptography/curve25519-dalek/blob/develop/benches/dalek_benchmarks.rs

**Comment by Messjer** [comment]
Done in #10
