### ISSUE TITLE
Improve API of `sm3`

### ISSUE THREAD

**Issue by Messjer** [yogcrypt/yogcrypt#9]
The current API of `sm3` requires users to explicitly provide message length. This might lead to potential misuses. For example, the following code wrongly computes the digest (due to incorrect length input) without informing the user.

```
        let msg = [0x61_626300u32];

        let hash = sm3_enc(&msg, 512);
        // this assertion fails
        assert_eq!(
            hash,
            [
                0x66c7f0f4, 0x62eeedd9, 0xd1f2d46b, 0xdc10e4e2, 0x4167c487, 0x5cf2f7a2, 0x297da02b,
                0x8f4ba8e0
            ]
        );
```

Another problem of the API is that it awkwardly requires user to pad the message with 0's to fit in the `u32` blocks, which is error-prone. For example, the following code gives the digest of `0x0061_6263` instead of `0x6162_63`.

```
        let msg = [0x61_6263u32];

        let hash = sm3_enc(&msg, 24);
        // this assertion fails
        assert_eq!(
            hash,
            [
                0x66c7f0f4, 0x62eeedd9, 0xd1f2d46b, 0xdc10e4e2, 0x4167c487, 0x5cf2f7a2, 0x297da02b,
                0x8f4ba8e0
            ]
        );
```

One possible fix could be to modify the API so that it accepts a string as input, then after manually finding the length, this wrapper function may split the string into `&[u32]` for use of the core functions.

**Comment by Messjer** [comment]
Would it be a good idea to assume msg length is a multiple of 8? This way we can use `&[u8]`.

**Comment by mssun** [comment]
How about let's survey how other Rust's crypto libraries design their APIs and list here? Then, we can discuss pros and cons.

**Comment by Messjer** [comment]
Yes, as can be seen, they all use [u8] (or equivalent b"hello,world") as a minimum unit for input. I believe using this API would be more user-friendly.

**Comment by mssun** [comment]
Yes, agree.

**Comment by Messjer** [comment]
I changed the API of sm2/3 to use `&[u8]` in 52201d6c2431b241efaa044c505da2ea0bbf14b0 and  1eff82ee2f69abc7acb5903d29a9bf608198f18a. Currently sm4 API also accepts `[u32]` as input, I think maybe changing it to use `&[u8]` would be more adherent to conventions. What's your opinion?

For example, see
* RustCrypto: https://github.com/RustCrypto/block-ciphers
```
extern crate aes_soft as aes;
extern crate block_modes;

use block_modes::{BlockMode, BlockModeIv, Cbc};
use block_modes::block_padding::Pkcs7;
use aes::Aes128;

// create an alias for convinience
type Aes128Cbc = Cbc<Aes128, Pkcs7>;

let mut cipher = Aes128Cbc::new_varkey(key, iv).unwrap();
// buffer must have enough space for message+padding
let mut buffer = [0u8; 32];
// copy message to the buffer
buffer[..msg_len].copy_from_slice(msg);
let encrypted_msg = cipher.encrypt_pad(&mut buffer, msg_len).unwrap();

let mut cipher = Aes128Cbc::new_varkey(key, iv).unwrap();
let decrypted_msg = cipher.decrypt_pad(encrypted_data).unwrap();
```

**Comment by mssun** [comment]
Yes, agree.

**Comment by Messjer** [comment]
Done in #17.
